app.url=https://login.salesforce.com/?locale=in
browser=chrome
valid.username=testuser@example.com
valid.password=ValidPass@123
invalid.username=invalid@example.com
invalid.password=WrongPass@456
implicit.wait.seconds=5
explicit.wait.seconds=10
